spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&userUnicode=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        ejb: 
          interceptor: com.amin.gestiondestock.interceptor.Interceptor
    
server:
  port: 8086

flickr:
  apiKey: 4322fae6de24711fd053991dfb07d16f
  apiSecret: c61f0ee8d7a7bb9f
  appKey: 72157720843731122-8efe0f4e920d6349
  appSecret: 4aa4caa32dd8130c